import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1719817703266 implements MigrationInterface {
    name = 'Migration1719817703266'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "FK_03f1db6f9042c4bdc11d4ab060e"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP CONSTRAINT "FK_5fad66fbcb022b47f5fe06b808d"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP CONSTRAINT "PK_9f1519a181628acf427771de3df"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD CONSTRAINT "PK_9f1519a181628acf427771de3df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "FK_35f6b4e97a232d600ef77585265"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "FK_30c21c444ddb62f4fbad61d6ea2"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "PK_2d64b690d92c5ffcfd162cec31c"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "PK_2d64b690d92c5ffcfd162cec31c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "aiModelsId"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "aiModelsId" uuid`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_af025737329ad51c9683956bb6d"`);
        await queryRunner.query(`ALTER TABLE "Ai_models" DROP CONSTRAINT "PK_f22e5d209ad864c8acf0f82d63e"`);
        await queryRunner.query(`ALTER TABLE "Ai_models" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Ai_models" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Ai_models" ADD CONSTRAINT "PK_f22e5d209ad864c8acf0f82d63e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_c7ab832a1ee466f0e90bd883dd7"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_697fda06c24ec0fa20216e636d0"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "PK_937fd98280534d2a1a7c20c4871"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "PK_937fd98280534d2a1a7c20c4871" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "aiModelsId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "aiModelsId" uuid`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "couponsId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "couponsId" uuid`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "FK_963ca9f303cf41616dd1925793b"`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "PK_2418d6bce705c88195d11a98547"`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "PK_2418d6bce705c88195d11a98547" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "couponTemplateId"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "couponTemplateId" uuid`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" DROP CONSTRAINT "PK_35a1af02c819c57647287ea8694"`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" ADD CONSTRAINT "PK_35a1af02c819c57647287ea8694" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Corporates" DROP CONSTRAINT "PK_e1df2f910f55b07c3adba6ca55e"`);
        await queryRunner.query(`ALTER TABLE "Corporates" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Corporates" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Corporates" ADD CONSTRAINT "PK_e1df2f910f55b07c3adba6ca55e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP CONSTRAINT "FK_62a3ff59fa986d93642549dbf92"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP CONSTRAINT "PK_36da7cca592af12bf7f52dfcc4a"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD CONSTRAINT "PK_36da7cca592af12bf7f52dfcc4a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP COLUMN "apiKeysId"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD "apiKeysId" uuid`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP CONSTRAINT "FK_643252c882d50d0f2e1eafaad6f"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP CONSTRAINT "PK_0dc3247a21b08e207fc79926863"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD CONSTRAINT "PK_0dc3247a21b08e207fc79926863" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP COLUMN "apiKeysId"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD "apiKeysId" uuid`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP CONSTRAINT "FK_8393df7d8e545627144988dad78"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP CONSTRAINT "PK_80d5f27ab47ab41fb978527a248"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD CONSTRAINT "PK_80d5f27ab47ab41fb978527a248" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP CONSTRAINT "FK_36410a1f2a4ae8737825d3e7b1a"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "PK_16d4f7d636df336db11d87413e3"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "PK_16d4f7d636df336db11d87413e3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP CONSTRAINT "PK_e69d70afb2d0c93e7aad03aa8e2"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD CONSTRAINT "PK_e69d70afb2d0c93e7aad03aa8e2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD CONSTRAINT "FK_5fad66fbcb022b47f5fe06b808d" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "FK_35f6b4e97a232d600ef77585265" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "FK_30c21c444ddb62f4fbad61d6ea2" FOREIGN KEY ("aiModelsId") REFERENCES "Ai_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_c7ab832a1ee466f0e90bd883dd7" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_af025737329ad51c9683956bb6d" FOREIGN KEY ("aiModelsId") REFERENCES "Ai_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_697fda06c24ec0fa20216e636d0" FOREIGN KEY ("couponsId") REFERENCES "Coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "FK_03f1db6f9042c4bdc11d4ab060e" FOREIGN KEY ("couponTemplateId") REFERENCES "Coupon_Template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "FK_963ca9f303cf41616dd1925793b" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD CONSTRAINT "FK_62a3ff59fa986d93642549dbf92" FOREIGN KEY ("apiKeysId") REFERENCES "Api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD CONSTRAINT "FK_643252c882d50d0f2e1eafaad6f" FOREIGN KEY ("apiKeysId") REFERENCES "Api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD CONSTRAINT "FK_8393df7d8e545627144988dad78" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD CONSTRAINT "FK_36410a1f2a4ae8737825d3e7b1a" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP CONSTRAINT "FK_36410a1f2a4ae8737825d3e7b1a"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP CONSTRAINT "FK_8393df7d8e545627144988dad78"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP CONSTRAINT "FK_643252c882d50d0f2e1eafaad6f"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP CONSTRAINT "FK_62a3ff59fa986d93642549dbf92"`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "FK_963ca9f303cf41616dd1925793b"`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "FK_03f1db6f9042c4bdc11d4ab060e"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_697fda06c24ec0fa20216e636d0"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_af025737329ad51c9683956bb6d"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "FK_c7ab832a1ee466f0e90bd883dd7"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "FK_30c21c444ddb62f4fbad61d6ea2"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "FK_35f6b4e97a232d600ef77585265"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP CONSTRAINT "FK_5fad66fbcb022b47f5fe06b808d"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP CONSTRAINT "PK_e69d70afb2d0c93e7aad03aa8e2"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD CONSTRAINT "PK_e69d70afb2d0c93e7aad03aa8e2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "PK_16d4f7d636df336db11d87413e3"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "PK_16d4f7d636df336db11d87413e3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Refund_request" ADD CONSTRAINT "FK_36410a1f2a4ae8737825d3e7b1a" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP CONSTRAINT "PK_80d5f27ab47ab41fb978527a248"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD CONSTRAINT "PK_80d5f27ab47ab41fb978527a248" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_keys" ADD CONSTRAINT "FK_8393df7d8e545627144988dad78" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP COLUMN "apiKeysId"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD "apiKeysId" integer`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP CONSTRAINT "PK_0dc3247a21b08e207fc79926863"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD CONSTRAINT "PK_0dc3247a21b08e207fc79926863" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_key_ips" ADD CONSTRAINT "FK_643252c882d50d0f2e1eafaad6f" FOREIGN KEY ("apiKeysId") REFERENCES "Api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP COLUMN "apiKeysId"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD "apiKeysId" integer`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP CONSTRAINT "PK_36da7cca592af12bf7f52dfcc4a"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD CONSTRAINT "PK_36da7cca592af12bf7f52dfcc4a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Api_logs" ADD CONSTRAINT "FK_62a3ff59fa986d93642549dbf92" FOREIGN KEY ("apiKeysId") REFERENCES "Api_keys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Corporates" DROP CONSTRAINT "PK_e1df2f910f55b07c3adba6ca55e"`);
        await queryRunner.query(`ALTER TABLE "Corporates" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Corporates" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Corporates" ADD CONSTRAINT "PK_e1df2f910f55b07c3adba6ca55e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" DROP CONSTRAINT "PK_35a1af02c819c57647287ea8694"`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Refresh_token" ADD CONSTRAINT "PK_35a1af02c819c57647287ea8694" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "couponTemplateId"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "couponTemplateId" integer`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP CONSTRAINT "PK_2418d6bce705c88195d11a98547"`);
        await queryRunner.query(`ALTER TABLE "Coupons" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "PK_2418d6bce705c88195d11a98547" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "FK_963ca9f303cf41616dd1925793b" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "couponsId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "couponsId" integer`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "aiModelsId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "aiModelsId" integer`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP CONSTRAINT "PK_937fd98280534d2a1a7c20c4871"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "PK_937fd98280534d2a1a7c20c4871" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_697fda06c24ec0fa20216e636d0" FOREIGN KEY ("couponsId") REFERENCES "Coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_c7ab832a1ee466f0e90bd883dd7" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Ai_models" DROP CONSTRAINT "PK_f22e5d209ad864c8acf0f82d63e"`);
        await queryRunner.query(`ALTER TABLE "Ai_models" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Ai_models" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Ai_models" ADD CONSTRAINT "PK_f22e5d209ad864c8acf0f82d63e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Payment_records" ADD CONSTRAINT "FK_af025737329ad51c9683956bb6d" FOREIGN KEY ("aiModelsId") REFERENCES "Ai_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "aiModelsId"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "aiModelsId" integer`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Images" DROP CONSTRAINT "PK_2d64b690d92c5ffcfd162cec31c"`);
        await queryRunner.query(`ALTER TABLE "Images" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Images" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "PK_2d64b690d92c5ffcfd162cec31c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "FK_30c21c444ddb62f4fbad61d6ea2" FOREIGN KEY ("aiModelsId") REFERENCES "Ai_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Images" ADD CONSTRAINT "FK_35f6b4e97a232d600ef77585265" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP CONSTRAINT "PK_9f1519a181628acf427771de3df"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD CONSTRAINT "PK_9f1519a181628acf427771de3df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Coupon_Template" ADD CONSTRAINT "FK_5fad66fbcb022b47f5fe06b808d" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Coupons" ADD CONSTRAINT "FK_03f1db6f9042c4bdc11d4ab060e" FOREIGN KEY ("couponTemplateId") REFERENCES "Coupon_Template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
